### PR TITLE
Guy

### PR DESCRIPTION
**Pull request by theguymeyer**

### CODE REVIEW

**Comment by Tiim** [comment]
Thanks that you like my website, did you mean to make this pull request?

**Comment by theguymeyer** [comment]
Hi Tiim,

I did not, I was confused as to how to properly deploy and ended up causing
and unnecessary PR.
By the way thank you for the code and the groundwork you put in!!

Thanks,
Guy
ᐧ

**Comment by theguymeyer** [comment]
Just a quick question, how does github pages link to the index.html? I am
confused since the dist folder is omitted with the .gitignore, there are no
HTML files at the top level and only my README file is displaying on the
website https://guymeyer.me

Any help would be greatly appreciated!

Thanks,
Guy
ᐧ

**Comment by Tiim** [comment]
I don't quite remember how it works but you can see in the [deploy.yml file](https://github.com/Tiim/Tiim.github.io/blob/source/.github/workflows/deploy.yml#L27-L36) that I use the [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) action to publish to the master branch. You possibly have to set in the repo settings where the compiled files will be.

**Pull request closed without merging**
